[tools]
cmake = "latest"
go = "latest"
python = ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
zig = "latest"
node = ["lts", "latest"]
bun = "latest"
deno = "latest"
ruby = "latest"
lazygit = "latest"
ghq = "latest"

