[tools]
cmake = "latest"
go = "latest"
python = ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
zig = "latest"
node = ["lts", "latest"]
bun = "latest"
deno = "latest"
ruby = "latest"
lazygit = "latest"
ghq = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:npm-check-updates" = "latest"
"npm:esbuild" = "latest"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:du-dust" = "latest"
"cargo:fd-find" = "latest"
"cargo:genact" = "latest"
"cargo:git-delta" = "latest"
"cargo:zoxide" = "latest"
"cargo:watchexec-cli" = "latest"
"cargo:ripgrep" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:procs" = "latest"
"cargo:sccache" = "latest"
"cargo:hyperfine" = "latest"
"cargo:sheldon" = "latest"
"cargo:onefetch" = "latest"
"cargo:viu" = "latest"
"cargo:gping" = "latest"
"cargo:zellij" = "latest"
"cargo:stylua" = "latest"
"cargo:hexyl" = "latest"
"cargo:starship" = "latest"
"cargo:tokei" = "latest"
"cargo:skim" = "latest"
"cargo:license-generator" = "latest"
"cargo:xh" = "latest"
"cargo:tree-sitter-cli" = "latest"

[settings]
experimental = true

