vim.keymap.set("n", "<esc><esc>", "<cmd>nohlsearch<cr>")

vim.keymap.set("n", "<leader>a", "<cmd>vsplit<cr>")
vim.keymap.set("n", "<leader>s", "<cmd>split<cr>")

vim.keymap.set("n", "[b", "<cmd>bprevious<cr>")
vim.keymap.set("n", "]b", "<cmd>bnext<cr>")

vim.keymap.set("n", "<leader><leader>", "<cmd>Chowcho<cr>")
vim.keymap.set("n", "<leader>u", "<cmd>UndotreeToggle<cr><cmd>UndotreeFocus<cr>")
vim.keymap.set("n", "<leader>t", "<cmd>ToggleTerm<cr>")
vim.keymap.set("n", "<leader>g", "<cmd>LazyGit<cr>")
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-n>")

vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>")
vim.keymap.set("n", "<leader>fe", "<cmd>Telescope file_browser<cr>")
vim.keymap.set("n", "<leader>fr", "<cmd>Telescope frecency<cr>")
vim.keymap.set("n", "<leader>fw", "<cmd>Telescope frecency workspace=CWD<cr>")
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>")
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<cr>")
vim.keymap.set("n", "<leader>fk", "<cmd>Telescope keymaps<cr>")
vim.keymap.set("n", "<leader>fp", "<cmd>Telescope neoclip<cr>")

vim.keymap.set("n", "<space>f", function()
    vim.lsp.buf.format({ async = true })
end)
vim.keymap.set("n", "<space>a", "<cmd>Lspsaga code_action<cr>")
vim.keymap.set("n", "<space>d", "<cmd>Lspsaga hover_doc<cr>")
vim.keymap.set("n", "<space>r", "<cmd>Lspsaga rename<cr>")
vim.keymap.set("n", "<space>g", "<cmd>Lspsaga peek_definition<cr>")
vim.keymap.set("n", "<leader>l", "<cmd>Lspsaga lsp_finder<cr>")
vim.keymap.set("n", "<leader>o", "<cmd>SymbolsOutline<cr>")
vim.keymap.set("n", "<leader>x", "<cmd>TroubleToggle<cr>")
